version: '3'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - ./data:/app/data          
      - ./cert:/app/cert        
    environment:
      - NODE_ENV=development
      - PFX_PASSWORD=coaveC123    
    env_file:
      - .env                     
